### PR TITLE
Add JustMy.scss to "Frameworks"

### PR DESCRIPTION
**Pull request by kjbrum**

### CODE REVIEW

**Comment by tandavas** [comment]
Thanks for the suggestion, but this is a bit too niche for the list.

**Comment by kjbrum** [comment]
Just curious, what makes my framework more niche then the other ones listed?

**Comment by tandavas** [comment]
Hi @kjbrum ! 

`Another stupid SCSS framework, but it's just mine.` (Quoted from the [repository](https://github.com/kjbrum/justmy.scss) and the [documentation](http://kylebrumm.com/justmy.scss/)) sounds pretty niche to me. It would be a good idea to have a description explaining why the framework is useful to someone instead of just telling them _"another stupid SCSS framework"_.

[Foundation](https://github.com/zurb/foundation-sites) has a good example for this: 

> Foundation is the most advanced responsive front-end framework in the world. Quickly go from prototype to production, building sites or apps that work on any kind of device with Foundation. Includes a fully customizable, responsive grid, a large library of Sass mixins, commonly used JavaScript plugins, and full accessibility support.

Even better, [Sierra](https://github.com/sierra-library/sierra#whats-the-difference-with-other-scss-libraries) has a section explaining how theirs is different others: 

```
What's the difference with other SCSS libraries?

This is a micro SCSS library to help you build websites, without all the arbitrary selectors.

    ✓ Only 37.03 kB (8.9 kB gzipped)
    ✓ Modular
    ✓ 2 configurable grid systems (bootstrap and flexboxgrid)
    ✓ Adjust colors, borders, radius & sizes in the variables.scss file
    ✓ Responsive
```

Also, having more stars on the repository also help proving that the framework is not _niche_ (showing that it is useful for others, not just the creator).

So, maybe you could try adding more description and content to it. Then, try to post it around the communities like hackernews and reddit to get more feedback and stars?

Keep up the great work :)

**Comment by tandavas** [comment]
Another good example is your [Juice](https://github.com/kjbrum/juice) mixins that we merged in #16! That's a great description right there:

> Simplify your life. Juice is a collection of Sass mixins/functions that are used to minimize the work needed to apply styling/properties to elements. Juice is not just a collection to help with cross browser support, so it is best paired with autoprefixer, for the best possible browser compatibility. You can enable prefixing for the mixin if you would like by setting the $browser-prefixes variable to true.

Plus, it has 238 stars! I hope this help 😃

**Comment by kjbrum** [comment]
@tandavas Rigt on, thanks for the clarification! 👍

**Pull request closed without merging**
