### PR TITLE
Add Sassdash to Libraries and Mixins section

### PR DESCRIPTION
**Pull request by elektronik2k5**
Sassdash is awesome and is obviously missing from this list!

### CODE REVIEW

**Comment by tandavas** [comment]
Sassdash looks so cool!

Please put Sassdash at the bottom of the **Libraries and Mixins** section instead as mentioned in [Contributing.md](https://github.com/Famolus/awesome-scss/blob/master/contributing.md),

**Comment by elektronik2k5** [comment]
@tandavas I updated the PR. Should have read the guidelines first.

**Comment by tandavas** [comment]
Thank you for the rearrangement!

I just checked the link again. I think it would be a better idea to link it to https://github.com/davidkpiano/sassdash instead as it also contains the installation instructions and explanation of what Sassdash is as well. The current link only displays the ability of Sassdash, but no project description and how to install Sassdash. It might be confusing for the beginners to get things started.

What do you think?

**Comment by elektronik2k5** [comment]
@tandavas how about both? :)

**Comment by tandavas** [comment]
That will work. Thank you 😄

**Pull request merged**
